apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-mysql-mariadb-10-1-system-owner-discovery
  namespace: dvwa
spec:
  action: Block
  message: System owner discovery command execution denied
  process:
    matchPaths:
    - path: /usr/bin/who
    - path: /usr/bin/w
    - path: /usr/bin/id
    - path: /usr/bin/whoami
  selector:
    matchLabels:
      app: dvwa-mysql
      tier: backend
  severity: 3
  tags:
  - MITRE
  - MITRE_T1082_system_information_discovery
