apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: dvwa-web-cytopia-dvwa-php-8-1-maintenance-tool-access
  namespace: dvwa
spec:
  action: Block
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      app: dvwa-web
      tier: frontend
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
